### PR TITLE
Setup icons for _NET_WM_ICON

### LINKED ISSUE #36: set x icon
I see you have added icons, are you planning to make x aware of those icons so that window managers and panels can display them? I originally thought this was an issue with tint2 (the panel I use), but according to https://gitlab.com/o9000/tint2/-/issues/726 it's a problem with the individual applications

### PR DESCRIPTION
**Pull request by alanswanson**
Provide icons for (most) window managers that don't match an applications WM_CLASS property against their .desktop icon
entry.

Generated src/icons.h with 16x16 and 32x32 icons only;
convert-png-to-argb-c.sh zutty_16x16.png zutty_32x32.png > ../src/icons.h

Closes #36 where I know you want to avoid including an image blob but, at least with 16x16 and 32x32 icons only, this is lower code size than having to find, load and process icons before passing XChangeProperty and finally freeing them.

### CODE REVIEW

**Comment by tomszilagyi** [comment]
Neat!
Do you have a list of WMs for which this patch (having _NET_WM_ICON) does the trick?
Do you know of any WMs still not covered (I mean, WMs that customarily display app icons, but still won't, even with this patch)?

**Comment by alanswanson** [comment]
Should be almost all of them since most support EWMH but personally I use and have tested with _awesome_ (tiling screens full of zuttys) and _Enlightenment_ (whose own _terminology_ is pretty but its VT support often ruins the output).

Many thanks for creating zutty and appreciated reading the doc/blog on its details and comparisons.

**Comment by mones** [comment]
Hi @alanswanson, nice addition!
Nevertheless, I wonder why adding a generated file to git.
I think it could be better to just patch build process to generate it on the fly with the script, if possible, couldn't it?
Thanks!

**Comment by alanswanson** [comment]
Yes, we could generate it but the icons are constant, the file is small and it saves a user dependency on ImageMagick (though it's usually included on all distros).

**Comment by alanswanson** [comment]
Updated with gpg commit signature. I hadn't seen the merging block for signed commits only for some reason.

**Comment by tomszilagyi** [comment]
Even though I dislike this mechanism in general (as captured by my comment on #36), I admit that it seems useful enough for a sufficient subset of users to make it worth having. So I am going to spend some time testing this patch.

@alanswanson Are there any endianness concerns, i.e., would the generated header file work when compiled on a big-endian machine? Would it need to be re-generated? What specification I could find about NET_WM_ICON ([link](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html#idm46400537332544)) is not exactly clear. What are your thoughts?

**Comment by mones** [comment]
> Yes, we could generate it but the icons are constant, the file is small and it saves a user dependency on ImageMagick (though it's usually included on all distros).

What I meant is to generate the src/icons.h at build-time, before calling the compiler, so it's compiled in like any other source file. The user wouldn't require IM for running zutty, it'd just be a build-time dependency.

**Comment by alanswanson** [comment]
For source based distros, such as Gentoo which I use, that would still make ImageMagick a system dependency. My previous answers still applies.

**Comment by mones** [comment]
> For source based distros, such as Gentoo which I use, that would still make ImageMagick a system dependency. My previous answers still applies.

Even on Gentoo you could remove it after building, but I guess we're off-topic now ;-)

**Pull request closed without merging**
