### PR TITLE
Fix Chinese IME support.

### PR DESCRIPTION
**Pull request by WillyPillow**
Fix Chinese IME support, so that stuff like fcitx works.

Honestly, I have little experience with Xorg; this patch is created via trial and error and repeatedly comparing with <https://gist.github.com/Determinant/19bbecb6db35312861f6cf9f54fdd3a5>. Any criticism is thus appreciated.

### CODE REVIEW

**Comment by tomszilagyi** [comment]
Interesting change, fairly neat, potentially useful even, as I take it solves your particular problem (which you have not really described, and unfortunately I am not familiar with fcitx or anything like that). Feel free to describe this in as much detail and technical depth as you want.

Is there any way I can (manually) verify this patch on a Debian stable with a standard US keyboard? As in: 1. demonstrate (reproduce) the existing breakage. 2. demonstrate that the patch fixes said breakage. (I am willing to install any package in the standard Debian repos with apt-get if needed.) If yes, I would appreciate *detailed* and *precise* instructions, I don't have much time to do research.

Finally, could this be somehow tested as part of the automated tests (`test/keys.sh`)?

**Comment by tomszilagyi** [comment]
Please refer to issue #31 and the commit referenced therein (a call to XSetLocaleModifiers() was initially present, but removed due to complaints of it failing).

**Comment by tomszilagyi** [comment]
Thanks, great info! Let me spend some time digesting and testing this...
I think the `XSetLocaleModifiers` call is fine, I was just curious what you thought about it re: the earlier issue, but apparently we agree. :)
The earlier usage with the `@im=none` argument was copied from somewhere (example/tutorial code, I don't remember) and when #31 was reported, the call should have been reduced to what you put in (calling it with the empty argument) instead of completely removed.
Don't bother with cooking up an automated test for this, it's fine if I can manually convince myself that it works as the code change is small and neat. And your video is great, thanks for taking the time making and sharing it!

**Comment by WillyPillow** [comment]
For whatever reason, I can't get the compose key to work with Zutty *at all* in Gnome... Pressing `Compose+' e` sends `\xe9` in Zutty but works fine in other applications.

Can you share your environment variables so that I can double-check that, e.g., my locale settings are correct?

**Comment by tomszilagyi** [comment]
Absolutely, see below. I am dumping this right from within Zutty. I can also add that running `xev` and pressing right control (which is the compose key set in gnome tweaks) in it gets reported as the `Multi_key` (which is the X keysym for the compose key), and (naturally) Zutty never sees that as it gets filtered out.

I removed a few clearly irrelevant entries (such as `LS_COLORS`) from the below list and sorted it. Let me know if you would like me to check anything else.

```
CLUTTER_IM_MODULE=ibus
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=gnome
DISPLAY=:2
EDITOR=emacsclient -t
GDMSESSION=gnome
GDM_LANG=en_US.UTF-8
GIO_LAUNCHED_DESKTOP_FILE=/home/tom/.local/share/applications/zutty.desktop
GIO_LAUNCHED_DESKTOP_FILE_PID=81630
GJS_DEBUG_OUTPUT=stderr
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
GNOME_SETUP_DISPLAY=:3
GTK_IM_MODULE=ibus
GTK_MODULES=gail:atk-bridge
IM_CONFIG_CHECK_ENV=1
IM_CONFIG_PHASE=1
INVOCATION_ID=a9ca5f9b9ddb44d6973f6199faa82007
JOURNAL_STREAM=8:508300
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LD_LIBRARY_PATH=/home/tom/root/lib:/usr/local/lib
LOGNAME=tom
MANAGERPID=30409
PWD=/home/tom
QT_ACCESSIBILITY=1
QT_IM_MODULE=ibus
SESSION_MANAGER=local/lepke:@/tmp/.ICE-unix/80672,unix/lepke:/tmp/.ICE-unix/80672
SHELL=/bin/bash
SHLVL=1
TERM=xterm-256color
USER=tom
USERNAME=tom
WAYLAND_DISPLAY=wayland-0
WINDOWID=8388610
WINDOWPATH=7
XAUTHORITY=/run/user/1000/.mutter-Xwaylandauth.3502J1
XDG_CURRENT_DESKTOP=GNOME
XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share/:/usr/share/
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_CLASS=user
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=wayland
XMODIFIERS=@im=ibus
ZUTTY_VERSION=0.11-4-g243bae9
_=/usr/bin/env
```

**Pull request closed without merging**
